name: Docker Build and Push

on:
  release:
    types: [created]

jobs:
  push_to_github_registry:
    name: Push Docker image to GHCR
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Set build tag name
        id: build_tag_name
        run: |
          echo ::set-output name=tag::ghcr.io/remotelock/kinesis-to-kafka:${GITHUB_REF#refs/tags/v}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
        with:
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.build_tag_name.outputs.tag }}
